### ISSUE TITLE
Remove the "m-dash-ui" class namespace from buttons so it works independently

### ISSUE THREAD

**Issue by diogobeda** [Mudano/m-dash-ui#25]
https://github.com/Mudano/m-dash-ui/blob/6b7651a0469a5f26f8cbec785a33106acf29ab01/components/buttons/Button.scss#L1

**Comment by dcorb** [comment]
Fixed here https://github.com/Mudano/m-dash-ui/commit/97b5b29bf6b3f69653cd758d28b834e90887a2ba
