### ISSUE TITLE
min-width in isotope item styling

### ISSUE THREAD

**Issue by hkmarques** [Mudano/m-dash-ui#74]
If an `m-card` is inside an `Iso` container, this is what happens:
![screen_shot_2017-11-16_at_11 40 40](https://user-images.githubusercontent.com/1238936/32894889-59c55850-cac5-11e7-8187-bde165568ed4.png)

The culprits:
![screen_shot_2017-11-16_at_11 40 59](https://user-images.githubusercontent.com/1238936/32894898-6062544c-cac5-11e7-9ab2-5a1ca6908be4.png)
![screen_shot_2017-11-16_at_11 41 08_360](https://user-images.githubusercontent.com/1238936/32894903-62e88998-cac5-11e7-84e9-f7a2bf11e5e0.png)

After removing `min-width` from both rules:
![screen_shot_2017-11-16_at_11 41 32_360](https://user-images.githubusercontent.com/1238936/32894916-6d580548-cac5-11e7-803f-0c221a7a75b5.png)

**Comment by diogobeda** [comment]
Fixed by #75
